# The filename MUST match the Command / AssemblyName (SkylineToolTemplate.exe).
Command = SkylineToolTemplate.exe
Arguments = $(SkylineConnection)
Title = SkylineToolTemplate
InitialDirectory =
OutputToImmediateWindow = False
